
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 1.0, "MC"]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets.
	"Biome Temperatures" = [["alexscaves:abyssal_chasm", 38.0, 40.0, "F"], ["minecraft:meadows", 55, 65.0, "F"], ["alexscaves:toxic_caves", 95.0, 95.0, "F"], ["minecraft:savanna_plateau", 76.0, 98.0, "F"], ["minecraft:taiga", 44.0, 62.0, "F"], ["minecraft:eroded_badlands", 88.0, 120.0, "F"], ["minecraft:savanna", 70.0, 95.0, "F"], ["incendium:volcanic_deltas", 112.0, 118.0, "F"], ["minecraft:swamp", 72.0, 84.0, "F"], ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], ["alexscaves:magnetic_caves", 52.0, 54.0, "F"], ["alexscaves:forlorn_hollows", 42.0, 46.0, "F"], ["minecraft:frozen_peaks", 15.0, 33.0, "F"], ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], ["minecraft:snowy_beach", 38.0, 52.0, "F"], ["minecraft:deep_dark", 63.0, 63.0, "F"], ["minecraft:warm_ocean", 67.0, 76.0, "F"], ["minecraft:windswept_forest", 48.0, 66.0, "F"], ["minecraft:jungle", 76.0, 87.0, "F"], ["minecraft:snowy_slopes", 24.0, 38.0, "F"], ["minecraft:stony_shore", 50.0, 64.0, "F"], ["minecraft:soul_sand_valley", 53.0, 53.0, "F"], ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], ["minecraft:desert", 48.0, 115.0, "F"], ["minecraft:snowy_taiga", 19.0, 48.0, "F"], ["incendium:toxic_heap", 94.0, 102.0, "F"], ["minecraft:badlands", 84.0, 120.0, "F"], ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], ["minecraft:river", 60.0, 70.0, "F"], ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], ["minecraft:windswept_savanna", 67.0, 90.0, "F"], ["minecraft:wooded_badlands", 80.0, 108.0, "F"], ["alexscaves:primordial_caves", 85.0, 85.0, "F"]]

["Block Temperature"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>, <*predicates>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the maximum temperature change this block can cause to a player (even with multiple blocks)
	#predicates: the state that the block has to be in for the temperature to be applied (lit=true for a campfire, for example).
	#Multiple predicates can be used by separating them with commas (i.e: "lit=true,waterlogged=false")
	BlockTemps = [["minecraft:soul_fire", -0.476, 7, true, 0.8], ["minecraft:fire", 0.476, 7, true, 0.8], ["'immersive_weathering:charred_log'", 0.2, 7, true, 0.4, "smoldering=true"], ["minecraft:magma_block", 0.5, 3, true, 0.6], ["woodentoolsremoved:firepit_block", 0.5, 7, true, 0.6, "lit=true"], ["minecraft:campfire", 0.5, 7, true, 0.6, "lit=true"], ["minecraft:soul_campfire", -0.476, 3, true, 0.6, "lit=true"], ["minecraft:ice", -0.15, 4, true, 0.5], ["minecraft:packed_ice", -0.25, 4, true, 1.0], ["minecraft:blue_ice", -0.35, 4, true, 1.0], ["tfmg:flarestack", 0.7, 4, true, 0.7, "lit=true"], ["immersive_weathering:thin_ice", -0.15, 4, true, 0.5], ["immersive_weathering:permafrost", -0.1, 3, true, 0.2], ["create:blaze_burner", 0.476, 6, true, 0.5, "blaze=smouldering"], ["create:blaze_burner", 0.8, 6, true, 1.4, "blaze=kindled"], ["create:blaze_burner", 1.6, 6, true, 1.9, "blaze=seething"], ["farmersdelight:stove", 0.28, 2, true, 0.35], ["immersive_weathering:fire", 0.476, 7, true, 0.8], ["immersive_weathering:soul_fire", -0.476, 7, true, 0.8], ["tfmg:coke_oven", 1.0, 2, true, 0.6, "controller_type=middle_on"], ["handcrafted:oven", 0.3, 2, true, 0.4], ["nethersdelight:blackstone_furnace", 0.41, 2, true, 0.5], ["quark:deepslate_furnace", 0.4, 2, true, 0.6], ["tfmg:exhaust", 0.5, 1, true], ["tfmg:air_intake", -0.3, 7, true, 1.0], ["railways:smokestack_diesel", -0.3, 7, true, 0.7, "enabled=true"], ["alexscaves:nuclear_furnace_component", 0.8, 3, true, 0.8, "active=true"], ["spelunkers_charm:deepslate_geyser_lava", 2.8, 3, false], ["spelunkers_charm:deepslate_geyser_water", 1.3, 5, false], ["spelunkers_charm:encased_geyser_on", 2.1, 2, false], ["create:chocolate", 0.2, 4, true, 0.6], ["alexcaves:acid", 0.3, 4, true, 2.1], ["tfmg:molten_steel", 2.1, 6, true, 2.4], ["tfmg:molten_slag", 2.1, 6, true, 2.4], ["spelunkery:spring_water", 0.1, 5, true, 0.4]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0

[Hearth]
	#How strong the hearth is
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "architects_palette:twisted_leaves", "alexscaves:ancient_leaves", "quark:blue_blossom_leaves", "quark:lavender_blossom_leaves", "quark:orange_blossom_leaves", "quark:yellow_blossom_leaves", "quark:red_blossom_leaves", "quark:ancient_leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

