
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.morelapis]
			lapis = false

#Disables specific entries
[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			nightstand = true
			cupboard = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			drawer = true
			pillar_trim = true
			side_table = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			board_slab = true
			boards = true
			board_wall = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.dramaticdoors]
			short_door = true
			tall_door = true

		[entries.wood_type.workshop_for_handsome_adventurer]
			dual_table_bottom_left = true
			tool_rack_double = true
			potion_shelf = true
			book_shelf_minimal = true
			simple_table = true
			book_shelf_open_double = true
			tool_rack_framed = true
			tool_rack_single = true
			book_shelf_double = true
			book_shelf_open_minimal = true
			dual_table_top_right = true
			dual_table_top_left = true
			tool_rack_pframed = true
			book_shelf_with_lanterns = true
			dual_table_bottom_right = true
			workstation_placer = true

