#Set the amount of kills to reach a milestone.
#Range: > 1
tallyMilestone = 25
#Percentage increase of player's damage against tallied mob per milestone. Set 0 to disable increase.
#Range: 0 ~ 100
tallyAttack = 5
#Maximum percentage buff of the player's damage against tallied mob they can attain. Set 0 to have no buff limit.
#Range: > 0
tallyAttackLimit = 0
#Percentage increase of player's defense against tallied mob per milestone. Set 0 to disable increase.
#Range: 0 ~ 100
tallyDefense = 5
#Maximum percentage buff of the player's defense against tallied mob they can attain. Set 0 to have no buff limit.
#Range: > 0
tallyDefenseLimit = 0
#Only works if tallyLooting is enabled. Defines the amount of kills to increase looting level. Best if value is higher than tallyMilestone.
#Range: > 1
tallyLootingMilestone = 100
#Only works if tallyLooting is enabled. The maximum looting level the player can attain from looting milestones.
#Range: > 1
tallyMaxLootingLevel = 3
#Only works if tallyExperience is enabled. Defines how much experience is increased after player reaches a milestone.
#Range: > 1
tallyExperienceIncrease = 2
#Maximum experience increase against tallied mob players can attain. Set 0 to have no limit.
#Range: > 0
tallyExperienceLimit = 0
#Whether kills by pets or owned mobs count to player's tally.
petTally = true
#Whether pets or owned mobs also gain attack buffs from player's tally.
petTallyAttack = true
#Whether pets or owned mobs also gain defense buffs from player's tally.
petTallyDefense = true
#Whether pets or owned mobs also gain looting buffs from player's tally.
petTallyLooting = true
#Reaching a certain milestone amount will increase looting against the mob type.
tallyLooting = true
#Reaching a milestone amount will increase experience drop from the mob type.
tallyExperience = true
#Shows in player's chat if they have reached a milestone
milestoneChat = true

